#release configuration
#Wed Mar 11 10:38:45 CET 2026
projectVersionPolicyId=default
scm.tagNameFormat=@{project.artifactId}-@{project.version}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
pushChanges=true
completedPhase=scm-check-modifications
scm.url=scm\:git\:https\://github.com/lutece-platform/lutece-wf-module-workflow-formstopdf.git
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
